### ISSUE TITLE
2階層目の要素数が多いと要素が画面をはみ出してしまう

### ISSUE THREAD

**Issue by kentosasa** [Hikaru-Ito/MagicTV#8]
表示returnが見えなくなるとか
[![https://gyazo.com/9b9cebc3452b64f73b789d3372bd2f3e](https://i.gyazo.com/9b9cebc3452b64f73b789d3372bd2f3e.png)](https://gyazo.com/9b9cebc3452b64f73b789d3372bd2f3e)

**Comment by Hikaru-Ito** [comment]
実装した
